site_name: Working with Azure Virtual Network Manager - Workshop
site_description: Working with Azure Virtual Network Manager - Workshop
site_author: Infrastructure as Code Oslo

nav:
  - Homepage: index.md
  - Prerequisites: prerequisites.md
  - Lab 01 - Provision lab resources: labs/lab-01/index.md
  - Lab 02 - Managing Virtual Networks IP addresses using AVNM IPAM: labs/lab-02/index.md
  - Lab 03 - Segmenting virtual networks with Network Groups: labs/lab-03/index.md
  - Lab 04 - Implementing hub-and-spoke network topology with AVNM: labs/lab-04/index.md
  - Lab 05 - Secure virtual networks using AVNM rule-set: labs/lab-05/index.md
  - Lab 06 - Routing spoke-to-spoke and spoke-to-internet traffic via Azure Firewall: labs/lab-06/index.md
  - Lab 07 - Cleaning up resources: labs/lab-07/index.md
theme:
  name: material
  font:
    text: Ubuntu
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - header.autohide
    - navigation.instant
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github
  logo: assets/images/02237-icon-service-Network-Managers.svg
  favicon: assets/images/02237-icon-service-Network-Managers.svg

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.keys
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.snippets:
      check_paths: true
      url_download: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - toc:
      toc_depth: 4
      permalink: true

copyright: Copyright &copy; 2023 Infrastructure as Code Oslo

plugins:
  - search
  - tags
  
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/iac-oslo/avnm-labs
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

extra_css:
  - assets/stylesheets/extra.css

repo_url: https://github.com/iac-oslo/avnm-labs